// src/constants/Constants.ts

const Constants = {
    PREF_KEY_APP_SERVER_API_BASE_URL: 'appserverbaseurl',
    DATAWITHGOAL: 0,
    DATAWITHOUTGOAL: 1,
    
    PREF_DEVICE_ID: 'deviceID',
    LOGIN_GEO: 'Geo_coordinates',
    PREF_KEY_ORGANIZATION: 'Organization',
    PREF_AUTHENTICATION_KEY: 'apiKey',
    ID: 'ID',

    USER_ID: 'userID',
    INFO: 'info',
    CONTENT: 'content',
    TYPE: 'type',
    PREF_INFO_TYPE: 'android',
    ANDROID: 'Android',
    PLATFORM_NAME: 'platformName',
    MOBILE_PLATFORM_TYPE: 'mobile',
    VERSION_CODE: 'versionCode',
    VERSION_STRING: 'versionString',

    ERROR_NO_NETWORK: 'No Network Connection',
    SERVER_ERROR: 'Server not found',
    NO_DATA_CONTENT: 'No data',
    ERROR_TAG: 'Failure',
    REFUSE: 'refused',
    SERVER_NOT_FOUND: 'Server is not reachable',
    ALREADY_LOGIN: 'Already login',

    OUTPUT_TYPE: 'outputType',
    PREF_JSON: 'json',
    PLATFORM_TYPE: 'platformType',
    ORGANIZATION_NAME: 'organizationName',
    SERVER_URL: 'serverURL',
    LOGIN_NAME: 'loginName',
    PASSWORD: 'password',
    SID: 'SID',
    IP_ADDRESS: 'ipaddress',
    GPS_COORDINATES: 'gpsCoordinate',

    AUTHORIZATION: 'Authorization',
    DATA: 'data',
    PREF_KEY_SELECTED_EVENT: 'selectedevent',

    ACTION_TYPE: 'actionType',
    ACTION: 'action',
    ROLE: 'role',

    JSON: 'json',
    IS_NOTIFICATION_ENABLED: 'isNotificationEnabled',

    ACTION_TYPE_SHOWALL: 'showall',
    ACTION_TYPE_SHOW: 'show',
    ACTION_TYPE_ADD: 'add',
    ACTION_TYPE_UPDATE: 'update',
    ACTION_TYPE_DELETE: 'delete',
    ACTION_TYPE_FORGOT: 'forgot',
    ACTION_TYPE_RESET: 'reset',

    SELECTED_ITEM: 'selectedItem',
    OTP: 'otp',
    SERIAL_ID: 'serialNo',
    AMOUNT: 'amount',
    DISCOUNT: 'discount',

    SERVICE_ITEM_ID: 'ID',
    SERVICE_ITEM_NAME: 'name',
    SERVICE_ITEM_TYPE: 'type',
    SERVICE_ITEM_DESCRIPTION: 'description',
    SERVICE_ITEM_STATUS: 'status',
    SERVICE_ITEM_BEGIN_DATE: 'beginDate',
    SERVICE_ITEM_END_DATE: 'endDate',
    SERVICE_ITEM_URL: 'url',
    SERVICE_ITEM_IMAGE_URL: 'imageUrl',
    SERVICE_ITEM_ARCHIVED: 'archived',
    SERVICE_ITEM_DATE: 'date',
    SERVICE_ITEM_DATEINTERVAL: 'dateInterval',

    ACTION_BY: 'actionBy',
    MESSAGE_SUCCESS: 'SUCCESS',
    LAST_NAME: 'lastName',
    FIRST_NAME: 'firstName',
    MOBILE: 'mobile',
    PHONE: 'phone',
    EMAIL: 'email',
    GENDER: 'gender',
    DOB: 'dob',
    INTERESTS: 'interests',
    NEWSLETTERS: 'newsLetters',
    STREET1: 'street1',
    STREET2: 'street2',
    CITY: 'city',
    STATE: 'state',
    COUNTRY: 'country',
    ZIPCODE: 'zipcode',
    ADDRESSDETAILS: 'address',
    SERVICE_NAME: 'serviceName',
    DESCRIPTION: 'description',
    IMAGE: 'Image',
    COLOR: 'Color',

    GOAL_ID: 'goalID',
    GOAL_NAME: 'goalName',
    GOAL_TYPE: 'goalType',
    GOAL_BEGIN_DATE: 'goalBeginDate',
    GOAL_END_DATE: 'goalEndDate',
    GOAL_URL: 'goalUrl',
    GOAL_ARCHIVED: 'archived',
    GOAL_DESCRIPTION: 'goalDescription',
    GOAL_DATEINTERVAL: 'dateInterval',
    GOAL_STATUS: 'goalStatus',
    GOAL_CATEGORY: 'category',

    ARCHIVE: 'archive',
    REASON: 'reason',

    CURRENT_DATEANDTIME: 'currentDateTime',
    CURRENT_TIMEZONE: 'currentTimezone',

    SERVICE_ID: 'serviceID',
    SERVICE_TYPE: 'serviceType',
    SERVICE_IS_SEARCHABLE: 'isSearchable',
    SERVICE_IS_APPLEVEL: 'isAppLevelService',
    SERVICE_STATUS: 'serviceStatus',

    EXERCISE: 'Exercise',
    MEASURE: 'Measure',
    MEDICATION: 'Medication',
    FOOD: 'Food',
    WEBSITES: 'Websites',
    MEETING: 'Meetings',
    EVENT: 'Events',
    BOOK: 'Books',

    EXERCISE_UC: 'EXERCISE',
    MEASURE_UC: 'MEASURE',
    MEDICATION_UC: 'MEDICATION',
    FOOD_UC: 'FOOD',
    TODO_UC: 'TODO',
    WEBSITES_UC: 'WEBSITE',
    MEETING_UC: 'MEETING',
    EVENT_UC: 'EVENT',
    BOOK_UC: 'BOOK',
    SEARCH_UC: 'FINDMENTOR',
    GOAL_UC: 'GOAL',

    MENTOR_UC: 'MENTOR',
    MENTEE_UC: 'MENTEE',

    SELECTED_TYPE: 'type',
    TEMPLATE: 'template',
    GOAL_TEMPLATE_ID: 'goalTemplateID',
    GOAL_DURATION: 'goalDuration',

    END_POINT_VERSION_HANDLER: 'versionchecker',

    APP_UPDATE_URL:
        'https://play.google.com/store/apps/details?id:com.nasotech.kavigai&ah:-YwxNJW7G6TMVi8o4xwmo-DJfsE',

    ABOUT_URL: 'https://app.kavigai.com/assets/about.html',
    CONTACT_URL: 'https://app.kavigai.com/assets/contact.html',
    PRIVACY_POLICY_URL: 'https://app.kavigai.com/assets/privacy_policy.html',
    TOS_URL: 'https://app.kavigai.com/assets/terms_of_service.html',
    HELP_URL: 'https://app.kavigai.com/assets/help.html',
} as const;

export type ConstantsKeys = keyof typeof Constants;

export default Constants;
